### ISSUE TITLE
Unity IL2CPP backend seems not to be supported when Managed Stripping Level set to High

### ISSUE THREAD

**Issue by SNMATAN** [Cysharp/ZString#13]
Due to Managed Stripping Level set to high - Unity could not resolve assembly "netstandard".
I am not sure whether this problem caused by Unity or by you.

Stacktrace:
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Unity.IL2CPP.Common.AssemblyResolver.ResolveInternal(AssemblyNameReference name)
   at Unity.IL2CPP.Common.AssemblyResolver.Resolve(AssemblyNameReference name)
   at Unity.IL2CPP.Common.WindowsRuntimeAwareMetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeNamedArgument(Collection`1& fields, Collection`1& properties)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeNamedArguments(UInt16 count, Collection`1& fields, Collection`1& properties)
   at Mono.Cecil.CustomAttribute.<Resolve>b__35_0(CustomAttribute attribute, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
   at Unity.Cecil.Visitor.Visitor.Visit(CustomAttribute customAttribute, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context)
   at Unity.IL2CPP.GenericsCollection.GenericContextFreeVisitor.Visit(MethodDefinition methodDefinition, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(ModuleDefinition moduleDefinition, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(AssemblyDefinition assemblyDefinition, Context context)

**Comment by SNMATAN** [comment]
Unity version 2019.3.9f1 - using only Text Mesh Pro package

**Comment by SNMATAN** [comment]
Be aware - I tried it on 2020.1.0b12 and it seems to be working =]

**Comment by jonny91** [comment]
Is it solved？

**Comment by neuecc** [comment]
Includes dlls(System.Buffers, Memory, etc...) etc., so it is not possible to support high.
Even in Manual, it appears that High can only be made to work in fairly limited circumstances.
https://docs.unity3d.com/Manual/ManagedCodeStripping.html
