### ISSUE TITLE
Mac os 13.4 Test("{0,-20} {1,5:F}", "Adam", decimal 40);

### ISSUE THREAD

**Issue by zhangda9010** [Cysharp/ZString#91]
Mac os 13.4
Test("{0,-20} {1,5:F}", "Adam", decimal 40);

Xunit.Sdk.XunitException: Expected actual to be 
"Adam                 40.000" with a length of 27, but 
"Adam                 40.00" has a length of 26, differs near "0" (index 25).
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences()
   at FluentAssertions.Primitives.StringValidator.Validate()
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs)
   at ZStringTests.FormatTest.Test[T0,T1](Boolean testUtf8, String format, T0 t0, T1 t1) in /Users/ruibinzhao/Downloads/ZString-master/tests/ZString.Tests/FormatTest.cs:line 31
   at ZStringTests.FormatTest.Test[T0,T1](String format, T0 t0, T1 t1) in /Users/ruibinzhao/Downloads/ZString-master/tests/ZString.Tests/FormatTest.cs:line 15
   at ZStringTests.CompositeFormatTest.AlignmentComponent() in /Users/ruibinzhao/Downloads/ZString-master/tests/ZString.Tests/CompositeFormatTest.cs:line 106
   at ConsoleApp.Program.Run() in /Users/ruibinzhao/Downloads/ZString-master/sandbox/ConsoleApp/Program.cs:line 32
   at ConsoleApp.Program.Main(String[] args) in /Users/ruibinzhao/Downloads/ZString-master/sandbox/ConsoleApp/Program.cs:line 23

**Comment by hadashiA** [comment]
Hello.
Your point is, in other words, the difference in the default number of digits in the "F" format.

```csharp
string.Format("{0:F}", 1f) // #=> "1.000"
ZString.Format("{0:F}", 1f) // #=> "1.00"
```

If the number of digits is important, you can specify the format string.

e.g) `ZString.Format("{0:F3}", 1f)` // #=> "1.000"
